
services:
  postgres:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./init/script.sql:/docker-entrypoint-initdb.d/init.sql
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

  django:
    build:
      context: .
      dockerfile: compose/local/Dockerfile
    env_file:
      - .env
    command: >
      bash -c "
      python manage.py migrate --noinput &&
      exec uvicorn config.asgi:application --host 0.0.0.0 --port 8000 --reload --workers 4
      "
    volumes:
      - ./:/app
      - ./requirements:/app/requirements
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - rabbitmq
      - redis

  celery:
    build:
      context: .
      dockerfile: compose/local/Dockerfile
    command: celery -A config worker -l info
    volumes:
      - .:/app
    depends_on:
      - rabbitmq
      - django
    env_file:
      - .env

  redis:
    image: redis:7-alpine
    container_name: cashmoov_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    env_file:
      - .env

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  postgres_data_dev:
  redis_data:
