services:
  redis:
    image: redis:7-alpine
    container_name: cashmoov_redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}
    # command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    # volumes:
    #   - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
    networks:
      - cashmoov_net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: cashmoov_rabbit
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    networks:
      - cashmoov_net

  django:
    image: ${DOCKER_ACCOUNT}/cashmoov-api:latest
    container_name: cashmoov_api
    pull_policy: always
    restart: unless-stopped
    env_file: .env
    command: >
      bash -c "python manage.py collectstatic --noinput &&
               python manage.py migrate --noinput &&
               uvicorn config.asgi:application --host 0.0.0.0 --port 8000"
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    networks:
      - cashmoov_net

  celery:
    image: ${DOCKER_ACCOUNT}/cashmoov-api:latest
    container_name: cashmoov_celery
    pull_policy: always
    restart: unless-stopped
    env_file: .env
    command: celery -A config worker -l info
    depends_on:
      - rabbitmq
      - django
    networks:
      - cashmoov_net

volumes:
  redis_data:


networks:
  cashmoov_net:
    external: true