# Generated by Django 5.1.15 on 2026-01-16 12:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.uuid4, max_length=255, unique=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField()),
                ('embedding', models.JSONField(null=True)),
                ('embedding_model', models.CharField(default='all-MiniLM-L6-v2', max_length=100)),
                ('source_type', models.CharField(choices=[('training', 'training'), ('conversation', 'conversation')], default='training', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
