# Generated by Django 5.1.15 on 2026-01-27 17:16

import uuid

import django.db.models.deletion
import pgvector.django.vector
from django.contrib.postgres.operations import CreateExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        CreateExtension("vector"),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(default=uuid.uuid4, max_length=255, unique=True),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("content", models.TextField()),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(dimensions=768, null=True),
                ),
                (
                    "embedding_model",
                    models.CharField(
                        default="intfloat/multilingual-e5-base", max_length=100
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("training", "training"),
                            ("conversation", "conversation"),
                        ],
                        default="training",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "slug",
                    models.SlugField(
                        default=None, editable=False, max_length=255, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=250, unique=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Chatbot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "slug",
                    models.SlugField(
                        default=None, editable=False, max_length=255, unique=True
                    ),
                ),
                ("username", models.CharField(max_length=250)),
                ("question", models.TextField()),
                ("answers", models.TextField(null=True)),
                ("used_for_training", models.BooleanField(default=False)),
                ("validated_for_training", models.BooleanField(default=False)),
                (
                    "group",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chatbots",
                        to="chatbot.group",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
