# Generated by Django 5.1.15 on 2026-02-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='question',
            field=models.TextField(null=True),
        ),
    ]
