# Generated by Django 5.1.15 on 2026-02-05 17:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, editable=False, max_length=255, unique=True),
        ),
    ]
