# Generated by Django 5.1.15 on 2026-01-21 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_chatbot_group_alter_document_embedding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbot',
            name='group_name',
        ),
        migrations.AddField(
            model_name='chatbot',
            name='answers',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='assistant_answer',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chatbot.group'),
        ),
    ]
