# Generated by Django 5.1.15 on 2026-03-06 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_add_embedding_index'),
        ('chatbot', '0002_alter_chatbot_question'),
    ]

    operations = [
    ]
