# Generated by Django 5.1.15 on 2026-01-21 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_remove_chatbot_group_name_chatbot_answers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chatbots', to='chatbot.group'),
        ),
        migrations.AlterField(
            model_name='document',
            name='embedding_model',
            field=models.CharField(default='intfloat/multilingual-e5-base', max_length=100),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
