# Generated by Django 5.1.15 on 2026-01-21 15:26

import cashmoov_api.users.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', cashmoov_api.users.managers.UserManager()),
            ],
        ),
    ]
