# Generated by Django 5.1.15 on 2026-01-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[("assistant", "assistant"), ("admin", "Admin")],
                default="assistant",
                max_length=20,
            ),
        ),
    ]
