name: CHECK_BEFORE_DEPLOY

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: "3.11"

jobs:
  check_syntax:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1

  check_dependencies:
    runs-on: ubuntu-latest
    needs: check_syntax
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install deps
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8

      - name: Run flake8
        run: flake8 . --exit-zero

  # security_audit:
  #   runs-on: ubuntu-latest
  #   needs: check_dependencies
  #   steps:
  #     - uses: actions/checkout@v4

  #     - uses: actions/setup-python@v5
  #       with:
  #         python-version: ${{ env.PYTHON_VERSION }}

  #     - name: Install deps
  #       run: pip install -r requirements.txt

  #     - name: Install pip-audit
  #       run: pip install pip-audit

  #     - name: Run pip-audit
  #       run: pip-audit -r requirements.txt --desc

  test:
    runs-on: ubuntu-latest
    needs: check_dependencies

    env:
      DATABASE_URL: postgresql://cashmoov:cashmoov@localhost:5432/cashmoov_test
      DEBUG: "False"
      DJANGO_SECRET_KEY: django-insecure-5pnnjh3p^m^-%$vv8+^px-3r(8g9g)a_5cck%y#dgqqb9@bak6
      DJANGO_SETTINGS_MODULE: config.settings
      CI: "true"

    services:
      postgres:
        image: pgvector/pgvector:pg16
        env:
          POSTGRES_USER: cashmoov
          POSTGRES_PASSWORD: cashmoov
          POSTGRES_DB: cashmoov_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run migrations
        run: python manage.py migrate

      - name: Run tests
        run: pytest -v
